### ISSUE TITLE
Auto completion doesn't work in migration files

### ISSUE THREAD

**Issue by joel-depiltech** [natanfelles/codeigniter-phpstorm#10]
Hello,
Thanks for your sharing. Your work make my life easier.
When I code in a migration file file (application/migrations/XXX_my_migration.php) I cannot auto complete, do you have an idea why this do not works ?
Thanks

Regards from Nice, France (so sorry for my english)

**Comment by natanfelles** [comment]
Hello, Joel.

I add a doc block inside my migration methods like it:

```php
	public function down()
	{
		/**
		 * @var CI_Controller $this
		 */
		$this->dbforge->drop_table($this->table);
	}
```

Then is possible to use code-completion with `$this->`.

I have not yet found a more elegant solution, but it works.

**Comment by joel-depiltech** [comment]
Many thanks @natanfelles ! It works well
