### ISSUE TITLE
Is it possible to use it for libraries

### ISSUE THREAD

**Issue by omkartapale** [natanfelles/codeigniter-phpstorm#11]
How do we integrate this for own CI Library? Is it possible?

**Comment by natanfelles** [comment]
Yes.

https://github.com/natanfelles/codeigniter-phpstorm/blob/master/phpstorm.php#L17

**Comment by omkartapale** [comment]
@natanfelles Means I have to add `@property` line for each library class in phpstorm.php file.

**Comment by omkartapale** [comment]
@natanfelles Thanks it works well.
