### ISSUE TITLE
CodeIgniter 4 

### ISSUE THREAD

**Issue by demortx** [natanfelles/codeigniter-phpstorm#12]
Powered by CodeIgniter 4?

**Comment by natanfelles** [comment]
No. Sorry. Hahah, CodeIgniter 4 do not need this.

CI 4 uses namespaces and the PHPDocs are being done with appropriated return types.

CodeIgniter 4 code-completion on good IDEs just works.

Please, see the References on this repo:  https://github.com/natanfelles/codeigniter-code-completion-for-sublimecodeintel
