### ISSUE TITLE
Use excluded path

### ISSUE THREAD

**Issue by innovation2you** [natanfelles/codeigniter-phpstorm#13]
Just a tip if you have same name class inside another directory (i.e. application/modules/_backup/module/controllers/module.php) folder make this:

Go to project directory folder "application/modules/_backup/" and mark directory as Excluded.

The Phpstorm index all folders, you need find that directory and mark as excluded.

Thanks for this awesome tip Natan!

**Comment by natanfelles** [comment]
Hahahhhah, wonderful tip. Thank you @gansoteles !
