### ISSUE TITLE
I use HMVC and I couldn't make it work.

### ISSUE THREAD

**Issue by mhmoalla** [natanfelles/codeigniter-phpstorm#16]
hi
I did all the steps and reviewed that couple of times carefully but it dose not work.
<img width="743" alt="screen shot 1397-06-16 at 9 19 59 am" src="https://user-images.githubusercontent.com/25548358/45199128-587d5680-b27f-11e8-8859-08902437f37c.png">

do I need to do anything with MY_controller?

**Comment by natanfelles** [comment]
Please, see the latest update.
