### ISSUE TITLE
does not see the models files

### ISSUE THREAD

**Issue by yuceltoluyag** [natanfelles/codeigniter-phpstorm#17]
Property 'product_model' not found in Product 

![phpstorm](https://i.ibb.co/RhYVTYs/Screenshot-2.png)

**Comment by natanfelles** [comment]
https://github.com/natanfelles/codeigniter-phpstorm/issues/1#issuecomment-230279189

**Comment by yuceltoluyag** [comment]
> [#1 (comment)](https://github.com/natanfelles/codeigniter-phpstorm/issues/1#issuecomment-230279189)
yes i saw that message but the problem persists.

Is there a place where I made a mistake, can you check it
phpstorm.php
```
/**
 * Models
 * @property   Product_model $product_model
 * @property   Sales_model $sales_model
 */
```

`$this->load->model("product_model","product_model");`

`$items = $this->product_model->getjson("product");`

**Comment by natanfelles** [comment]
Please, certify that the properties are in the top of the class:

```php
/**
 * Models
 * @property   Product_model $product_model
 * @property   Sales_model $sales_model
 */
class Product extend CI_Controller {
}

```

**Comment by yuceltoluyag** [comment]
solved ty
